name: on branch specific
on: push
  branches:
    - master
    - main
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: runs on ubuntu
        run: echo "hello this is branch based"
      
